default_stages: [commit, push]
fail_fast: false
exclude: ^.*/migrations/.*


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.16
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        name: ruff lint
        args: [ "--exit-non-zero-on-fix" ]
      - id: ruff-format
  - repo: https://github.com/djlint/djLint
    rev: v1.35.2
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst)$
        additional_dependencies:
          - tomli
