default_stages: [pre-commit, pre-push]
fail_fast: false
exclude: ^.*/migrations/.*


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: ruff lint
        args: [ "--exit-non-zero-on-fix" ]
      - id: ruff-format
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        args: ["--configuration=pyproject.toml"]
  - repo: https://github.com/crate-ci/typos
    rev: codespell-dict-v0.5.0
    hooks:
      - id: typos
        args:
          - --exclude
          - "static/general/dist/.*"

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.21
    hooks:
    - id: mdformat
      files: ^docs/.*
      types: [markdown]
      additional_dependencies:
      - mdformat-myst
  -   repo: https://github.com/biomejs/pre-commit
      rev: v0.6.1
      hooks:
      -   id: biome-check
          additional_dependencies: ["@biomejs/biome@1.9.2"]
  - repo: local
    hooks:
      - id: rustywind # Remove rustywind once biomejs tailwind sorting is competent: https://github.com/biomejs/biome/issues/1274
        name: Tailwind CSS Class sorter
        language: node
        additional_dependencies:
          - rustywind@latest
        entry: rustywind
        args: [--write]
        types_or: [html]
