# Generated by Django 5.1.3 on 2024-12-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerimage',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='dockeraction',
            name='operating_systems',
        ),
        migrations.AlterModelOptions(
            name='dockeraction',
            options={},
        ),
        migrations.AlterField(
            model_name='dockerimage',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='DockerOS',
        ),
    ]
