# Generated by Django 5.1.3 on 2024-12-29 04:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_dockerimage_operating_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ty', models.CharField(choices=[('create_site', 'Creating site'), ('rename_site', 'Renaming site'), ('edit_site_names', 'Changing site name/domains'), ('change_site_type', 'Changing site type'), ('create_site_database', 'Creating site database'), ('delete_site_database', 'Deleting site database'), ('regen_site_secrets', 'Regenerating site secrets'), ('update_resource_limits', 'Updating site resource limits'), ('update_docker_image', 'Updating site Docker image'), ('delete_site', 'Deleting site'), ('restart_site', 'Restarting site'), ('fix_site', 'Attempting to fix site')], max_length=24, verbose_name='type')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('started_time', models.DateTimeField(null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator(regex='^[a-z]+(_[a-z]+)+$')])),
                ('name', models.CharField(max_length=80)),
                ('started_time', models.DateTimeField(null=True)),
                ('result', models.BooleanField(default=None, null=True)),
                ('message', models.TextField(blank=True, help_text='Message describing the actions taken (and/or what failed). Should always be set to allow for easier debugging.\nOnly visible to superusers.')),
                ('user_recoverable', models.BooleanField(default=False, help_text='Can the user recover from this failure?')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.operation')),
            ],
        ),
    ]
