# Generated by Django 5.1.3 on 2024-12-29 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_remove_dockerimage_operating_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='placeholder_color',
            field=models.CharField(default='#000000', help_text='Enter a hex color code', max_length=7, validators=[django.core.validators.RegexValidator(message="This field must start with a '#' character.", regex='^#')]),
            preserve_default=False,
        ),
    ]
