# Generated by Django 5.1.3 on 2024-12-29 23:26

from django.db import migrations, models


def convert_mode(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    for site in Site.objects.using(db_alias).all():
        if site.mode == "D":
            site.mode = "dynamic"
        else:
            site.mode = "static"
        site.save()

def reverse_convert_mode(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    db_alias = schema_editor.connection.alias
    for site in Site.objects.using(db_alias).all():
        if site.mode == "dynamic":
            site.mode = "D"
        else:
            site.mode = "S"
        site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_operation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='mode',
            field=models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], max_length=10),
        ),
        migrations.RunPython(convert_mode, reverse_convert_mode),
    ]
