# Generated by Django 5.1.3 on 2025-03-25 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_site_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DockerAction',
        ),
        migrations.DeleteModel(
            name='DockerImage',
        ),
    ]
