# Generated by Django 5.1.3 on 2024-12-31 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_placeholder_color'),
        ('sites', '0004_alter_site_mode'),
    ]

    operations = [
    ]
