# Generated by Django 5.1.3 on 2025-03-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_delete_dockeraction_delete_dockerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='user_message',
            field=models.TextField(blank=True, help_text='User-facing message describing the actions taken (and/or what failed).'),
        ),
    ]
