# Generated by Django 5.1.3 on 2024-12-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_merge_20241231_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='placeholder_color',

        ),
    ]
