# Generated by Django 5.1.3 on 2024-12-31 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_remove_site_placeholder_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='placeholder_color',
            field=models.CharField(blank=True, help_text='Enter a hex color code', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
    ]
