[project]
name = "Manager"
version = "0.1.0"
description = "A next generation website hosting platform"
publish = false

[tool.mypy]
ignore_missing_imports = true
warn_unreachable = true
plugins = ["mypy_django_plugin.main"]

[tool.mypy.overrides]
module = "manager.apps.*.migrations.*"
ignore_errors = true

[tool.django-stubs]
django_settings_module = "manager.settings"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "manager.settings"
python_files = "tests.py test_*.py"
norecursedirs = ["media", "migrations"]
testpaths = "manager"
addopts = "--doctest-modules manager --import-mode=importlib -n auto"
doctest_optionflags = "NORMALIZE_WHITESPACE NUMBER"
