[project]
name = "Manager"
version = "0.1.0"
description = "A next generation website hosting platform"
dependencies = [
  "celery",
  "channels-redis>=4.2.1",
  "channels[daphne]",
  "daphne>=4.1.2",
  "django",
  "django-browser-reload",
  "django-cotton>=2.0.3",
  "django-debug-toolbar",
  "django-htmx",
  "django-linear-migrations",
  "lucide[django]>=1.1.3",
  "pillow",
  "psycopg[binary]",
  "pydenticon>=0.3.1",
  "redis",
  "requests",
  "social-auth-app-django",
  "typing-extensions",
]

[dependency-groups]
dev = [
  "colorama",
  "django-extensions",
  "django-fastdev",
  "watchdog",
]

lint = [
  "django-stubs",
  "pre-commit",
]

test = [
  "pytest",
  "pytest-django",
  "pytest-xdist",
  "responses",
]


[tool.uv]
package = false
default-groups = ["lint", "test", "dev"]

[tool.django-stubs]
django_settings_module = "director.settings"

[tool.djlint]
indent = 2
preserve_blank_lines = true
blank_line_after_tag="load,extends,include"
ignore="H006"  # Use tailwind w- and h- classes instead

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "director.settings"
python_files = ["tests.py", "test_*.py"]
norecursedirs = ["media", "migrations"]
testpaths = ["director"]
addopts = "--import-mode=importlib -n auto"
doctest_optionflags = "NORMALIZE_WHITESPACE NUMBER"
