name: CI setup
description: Install the dependencies needed for ci

inputs:
  groups:
    description: The dependency groups to install (blank for all).
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.x"
        python-version: 3.12

    - name: Install dependencies
      shell: bash
      run: ${{ github.action_path }}/uv-sync.sh ${{ inputs.groups }}
