name: CI setup
description: Install the dependencies needed for ci

inputs:
  group:
    description: The dependency group to install (blank for all).
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.6.x"
        python-version: 3.13

    - name: Install dependencies
      shell: bash
      run: |
        if [ -n "${{ inputs.group }}" ]; then
          exec uv sync --only-group "${{ inputs.group }}"
        fi
        exec uv sync
