name: CI setup
description: Install the dependencies needed for ci

inputs:
  python-version:
    description: The python version to install with uv
    required: false
    default: '3.12'
  groups:
    description: The dependency groups to install.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.x"
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: ${{ github.action_path }}/uv-sync.sh ${{ inputs.groups }}
