services:
  manager-celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../manager:/manager:z
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CELERY=1
    depends_on:
      - redis
      - manager-postgres
      - postgres
      - mysql

  manager-web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ../manager:/manager:z
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - manager-postgres
      - postgres
      - mysql

  redis:
    image: redis:alpine
    ports:
      - "6379"

  manager-postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432"
    volumes:
      - ./data/postgres-manager:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: manager

  postgres:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: director
      POSTGRES_PASSWORD: director
      POSTGRES_DB: director-postgres
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: director
      MYSQL_PASSWORD: director
      MYSQL_DATABASE: director-mysql
