# Generated by Django 5.1.3 on 2025-07-28 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_enable_trigram_extension'),
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='users_recen_user_id_f4683e_idx')],
                'unique_together': {('user', 'site')},
            },
        ),
    ]
