name: CI
on:
  - push
  - pull_request

env:
  CI: 1

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: './.github/actions/ci-setup'

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run mypy on Manager
        run: |
          cd manager
          uv run mypy director

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: './.github/actions/ci-setup'

      - name: Run Tests on Manager
        run: |
          uv run pytest -c "manager/pyproject.toml"

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: './.github/actions/ci-setup'

      - name: Build Docs
        run: |
          cd docs
          uv run make html SPHINXOPTS="-W --keep-going"
