name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --no-install-project --locked

      - name: Set env vars
        run: echo "CI=1" >> $GITHUB_ENV

      - name: Run Tests on Manager
        run: |
          uv run pytest -c "manager/pyproject.toml"

      - name: Run mypy on Manager
        run: |
          cd manager
          uv run mypy director

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --no-install-project --locked

      - name: Build Docs
        run: |
          cd docs
          uv run make html SPHINXOPTS="-W --keep-going"
