name: CI
on:
  - push
  - pull_request

env:
  CI: 1

defaults:
  run:
    shell: bash

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/ci-setup
        with:
          group: "lint"

      - name: Run pre-commit
        run: uv run pre-commit run --all-files --show-diff-on-failure

      - name: Run mypy on Orchestrator
        working-directory: orchestrator
        run: uv run --package orchestrator mypy orchestrator

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/ci-setup
        with:
          group: "test"

      - name: Check migrations
        working-directory: manager
        run: uv run --package manager python manage.py makemigrations --check --noinput

      - name: Migrate
        working-directory: manager
        run: uv run --package manager python manage.py migrate --noinput

      - name: Run Tests on Manager
        working-directory: manager
        run: uv run --package manager pytest

      - name: Run Tests on Orchestrator
        working-directory: orchestrator
        run: uv run --package orchestrator pytest

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/ci-setup
        with:
          group: "docs"

      - name: Install graphviz
        run: sudo apt install graphviz

      - name: Build Docs
        working-directory: docs
        run: uv run just html-strict
