name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --no-install-project --locked

      - name: Run Tests
        run: uv run pytest

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up repo
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.x"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --no-install-project --locked

      - name: Build Docs
        run: |
          cd docs
          uv run make html SPHINXOPTS="-W --keep-going"
