name: Deploy docs

on:
  push:
    branches: [main]

jobs:
  build:
    if: github.repository == 'JasonGrace2282/director5'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: './.github/actions/ci-setup'

      - name: Build docs
        working-directory: ./docs
        run: uv run make html

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
