services:
  redis:
    container_name: director_redis
    image: redis:latest
    networks:
      - director_net
    expose:
      - "6379"

  postgres:
    container_name: director_postgres
    image: postgres:latest
    networks:
      - director_net
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_PASSWORD=director
    volumes:
      - director-pgdata:/var/lib/postgresql/data

  celery:
    container_name: director_celery
    image: director_base
    entrypoint: uv run celery -A director worker --loglevel=INFO
    working_dir: /director5/manager
    networks:
      - director_net
    volumes:
      - ../../:/director5
      - /director5/.venv
    depends_on:
      - django

  celerybeat:
    container_name: director_celerybeat
    image: director_base
    entrypoint: uv run celery -A director beat --loglevel=INFO
    working_dir: /director5/manager
    networks:
      - director_net
    volumes:
      - ../../:/director5
      - /director5/.venv
    depends_on:
      - django

  django:
    container_name: director_django
    build:
      context: ../../
      dockerfile: ./dev/docker/Dockerfile.main
    image: director_base
    restart: on-failure
    networks:
      - director_net
    ports:
      - 8080:8080
    volumes:
      - ../../:/director5
      - /director5/.venv
    depends_on:
      - redis
      - postgres
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "django"

  fastapi:
    container_name: director_orchestrator
    image: director_base
    networks:
      - director_net
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8080
    volumes:
      - ../../:/director5
      - /director5/.venv
      - firecracker-socket:/tmp/firecracker-socket
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "fastapi"
    cap_add:
      - NET_ADMIN

  firecracker:
    container_name: director_firecracker
    stop_grace_period: 1s
    privileged: true
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.firecracker
    image: director_firecracker
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    volumes:
      - firecracker-socket:/tmp/firecracker-socket
      - .:/tmp/firecracker
    entrypoint:
      - "/tmp/firecracker/firecracker.sh"

  tailwind:
    container_name: director_tailwind
    image: director_base
    stop_grace_period: 1s
    tty: true
    networks:
      - director_net
    volumes:
      - ../../:/director5
      - /director5/.venv
    depends_on:
      - django
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "tailwind"

networks:
  director_net:
    driver: bridge

volumes:
  director-pgdata:
  firecracker-socket:
