services:
  redis:
    container_name: director_redis
    image: redis:latest
    networks:
      - director_net
    expose:
      - "6379"

  postgres:
    container_name: director_postgres
    image: postgres:latest
    networks:
      - director_net
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_PASSWORD=director
    volumes:
      - director-pgdata:/var/lib/postgresql/data

  celery:
    container_name: director_celery
    image: director_base
    entrypoint:
      - uv
      - run
      - -m
      - watchfiles
      - --filter
      - python
      - "uv run celery -A director worker"
      - /director5/manager/director
    working_dir: /director5/manager
    networks:
      - director_net
    volumes:
      - ../../:/director5
    depends_on:
      - redis

  django:
    container_name: director_django
    build:
      context: ../../
      dockerfile: ./dev/docker/Dockerfile
    image: director_base
    working_dir: /director5/manager
    restart: on-failure
    networks:
      - director_net
    ports:
      - 8080:8080
    volumes:
      - ../../:/director5
      - ../../docker/storage/:/data
    depends_on:
      - postgres
    entrypoint:
      - "/director5/dev/docker/docker-entrypoint.sh"
      - "django"

  fastapi:
    container_name: director_orchestrator
    image: director_base
    working_dir: /director5/orchestrator
    stop_grace_period: 1s
    networks:
      - director_net
    ports:
      - 8000:8080
    volumes:
      - ../../:/director5
      - ../../docker/storage/:/data
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint:
      - "/director5/dev/docker/docker-entrypoint.sh"
      - "fastapi"
    environment:
      PWD_HOST: "${PWD}"

  tailwind:
    container_name: director_tailwind
    image: director_base
    stop_grace_period: 1s
    tty: true
    networks:
      - director_net
    volumes:
      - ../../:/director5
    depends_on:
      - django
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "tailwind"

  director-traefik:
    image: traefik:v3.2
    container_name: traefik-reverse-proxy
    command:
      - --api.dashboard=true
      - --api.insecure=true
      # this runs traefik.localhost
      - --providers.file.filename=/traefik/traefik.yml
      # this runs the actual sites
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
    ports:
      - "80:80"
    volumes:
      - .:/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - director-sites

networks:
  director_net:
    driver: bridge
    name: director_net

  # the network the hosted sites run on
  director-sites:
    name: director-sites
    driver: overlay
    attachable: true

volumes:
  director-pgdata:
