services:
  redis:
    container_name: director_redis
    image: redis:latest
    networks:
      - director_net
    expose:
      - "6379"

  postgres:
    container_name: director_postgres
    image: postgres:latest
    networks:
      - director_net
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=director
      - POSTGRES_PASSWORD=director
    volumes:
      - pgdata:/var/lib/postgresql/data

  celery:
    container_name: director_celery
    image: director_base
    entrypoint: uv run celery -A director worker --loglevel=INFO
    working_dir: /director5/manager
    networks:
      - director_net
    volumes:
      - ../../:/director5:z
      - /director5/.venv
    depends_on:
      - django

  celerybeat:
    container_name: director_celerybeat
    image: director_base
    entrypoint: uv run celery -A director beat --loglevel=INFO
    working_dir: /director5/manager
    networks:
      - director_net
    volumes:
      - ../../:/director5:z
      - /director5/.venv
    depends_on:
      - django

  django:
    container_name: director_django
    build:
      context: ../../
      dockerfile: ./dev/docker/Dockerfile
    image: director_base
    networks:
      - director_net
    ports:
      - 8080:8080
    volumes:
      - ../../:/director5:z
      - /director5/.venv
    depends_on:
      - redis
      - postgres
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "django"

  fastapi:
    container_name: director_orchestrator
    image: director_base
    networks:
      - director_net
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - 80:8080
    volumes:
      - ../../:/director5:z
      - /director5/.venv
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "fastapi"

  tailwind:
    container_name: director_tailwind
    image: director_base
    stop_grace_period: 1s
    tty: true
    networks:
      - director_net
    volumes:
      - ../../:/director5:z
      - /director5/.venv
    depends_on:
      - django
    entrypoint:
      - "dev/docker/docker-entrypoint.sh"
      - "tailwind"

  firecracker:
    container_name: director_firecracker
    stop_grace_period: 1s
    image: director_base

    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - firecracker-socket:/tmp/firecracker-socket:z
      - .:/tmp/firecracker
    entrypoint: /tmp/firecracker/firecracker.sh

  apiproxy:
    container_name: director_apiproxy
    image: director_base
    ports:
      - "12345:12345"
    depends_on:
      - firecracker
    entrypoint:
      - socat
      - TCP-LISTEN:12345,,reuseaddr,fork
      - UNIX-CONNECT:/tmp/firecracker-socket/control.sock
    volumes:
      - firecracker-socket:/tmp/firecracker-socket


networks:
  director_net:
    driver: bridge

volumes:
  pgdata:
  firecracker-socket:
