# NOTE: This is only here to make sure traefik works
# Eventually, we should transition to HTTP based configs

http:
  routers:
    traefik-router:
      rule: "Host(`traefik.localhost`)"
      service: api@internal
