# sample:
# docker service create --name nginx-test --replicas 1 -l traefik.http.routers.nginx-test.rule="Host(\`example.localhost\`)" -l traefik.http.services.nginx-test.loadbalancer.server.port=80 nginx

http:
  routers:
    traefik-router:
      rule: "Host(`traefik.localhost`)"
      service: api@internal
